-- Collect TCG Beta 2026-09-24-v07
-- Phase 2B1: lightweight discovery attribution for Qualified Card Views.
-- Run this once in the Supabase SQL editor before relying on discovery history.
-- Rerunnable: table/index creation is idempotent and the RPC is replaced safely.
--
-- This migration intentionally does NOT alter existing analytics/engagement
-- tables or their RLS policies. Public clients receive no direct table access.

create table if not exists public.card_discovery_views (
  id bigint generated by default as identity primary key,
  card_id uuid not null references public.cards(id) on delete cascade,
  visitor_id text not null,
  discovery_source text not null,
  viewed_at timestamptz not null default now()
);

create index if not exists card_discovery_views_viewed_at_idx
  on public.card_discovery_views (viewed_at desc);

create index if not exists card_discovery_views_source_viewed_at_idx
  on public.card_discovery_views (discovery_source, viewed_at desc);

create index if not exists card_discovery_views_card_viewed_at_idx
  on public.card_discovery_views (card_id, viewed_at desc);

alter table public.card_discovery_views enable row level security;

revoke all on table public.card_discovery_views from anon, authenticated;

create or replace function public.record_card_discovery_view(
  p_card_id uuid,
  p_visitor_id text,
  p_source text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_visitor text := left(trim(coalesce(p_visitor_id, '')), 120);
  v_source text := lower(trim(coalesce(p_source, '')));
begin
  if p_card_id is null or v_visitor = '' then
    return false;
  end if;

  if v_source not in (
    'trending',
    'recently-added',
    'spotlight',
    'related',
    'vintage',
    'championship',
    'sealed',
    'search',
    'inventory-filtered',
    'inventory',
    'collection',
    'reserved',
    'sold',
    'recently-viewed',
    'favorites',
    'home'
  ) then
    return false;
  end if;

  if not exists (
    select 1
    from public.cards c
    where c.id = p_card_id
      and coalesce(lower(c.lifecycle_status), 'live') = 'live'
  ) then
    return false;
  end if;

  insert into public.card_discovery_views (
    card_id,
    visitor_id,
    discovery_source
  )
  values (
    p_card_id,
    v_visitor,
    v_source
  );

  return true;
end;
$$;

revoke all on function public.record_card_discovery_view(uuid, text, text) from public;
grant execute on function public.record_card_discovery_view(uuid, text, text) to anon, authenticated;

comment on table public.card_discovery_views is
  'Qualified card-view discovery attribution. No direct public table access; written through record_card_discovery_view().';

comment on function public.record_card_discovery_view(uuid, text, text) is
  'Records the discovery source for an already-qualified live-card view.';
