/** Preserve the V92 initialization order across the feature modules. */
import { initialize as initialize0 } from '../features/core/utilities.js';
import { initialize as initialize1 } from '../features/cards/favorites.js';
import { initialize as initialize2 } from '../features/inventory/ordering.js';
import { initialize as initialize3 } from '../features/media/collage.js';
import { initialize as initialize4 } from '../features/cards/repository.js';
import { initialize as initialize5 } from '../app/navigation.js';
import { initialize as initialize6 } from '../features/cards/pricing.js';
import { initialize as initialize7 } from '../services/catalogue.js';
import { initialize as initialize8 } from '../features/content/giveaways-data.js';
import { initialize as initialize9 } from '../features/content/showcase-data.js';
import { initialize as initialize10 } from '../services/analytics.js';
import { initialize as initialize11 } from '../features/owner/psa.js';
import { initialize as initialize12 } from '../app/routing.js';
import { initialize as initialize13 } from '../features/media/images.js';
import { initialize as initialize14 } from '../features/cards/presentation.js';
import { initialize as initialize15 } from '../features/owner/forms.js';
import { initialize as initialize16 } from '../features/content/home.js';
import { initialize as initialize17 } from '../features/inventory/filtering.js';
import { initialize as initialize18 } from '../features/cards/related.js';
import { initialize as initialize19 } from '../features/cards/tiles.js';
import { initialize as initialize20 } from '../features/content/giveaways.js';
import { initialize as initialize21 } from '../features/content/showcase.js';
import { initialize as initialize22 } from '../features/content/giveaway-pages.js';
import { initialize as initialize23 } from '../features/owner/insights.js';
import { initialize as initialize24 } from '../features/content/information.js';
import { initialize as initialize25 } from '../features/social/posts.js';
import { initialize as initialize26 } from '../features/owner/quality.js';
import { initialize as initialize27 } from '../features/owner/tools.js';
import { initialize as initialize28 } from '../features/owner/image-maintenance.js';
import { initialize as initialize29 } from '../features/owner/add.js';
import { initialize as initialize30 } from '../features/cards/details.js';
import { initialize as initialize31 } from '../features/owner/editor.js';
import { initialize as initialize32 } from '../app/theme.js';
import { initialize as initialize33 } from '../app/startup.js';

export function initializeApp(appContext,runtime){
  initialize0(appContext,runtime);
  initialize1(appContext,runtime);
  initialize2(appContext,runtime);
  initialize3(appContext,runtime);
  initialize4(appContext,runtime);
  initialize5(appContext,runtime);
  initialize6(appContext,runtime);
  initialize7(appContext,runtime);
  initialize8(appContext,runtime);
  initialize9(appContext,runtime);
  initialize10(appContext,runtime);
  initialize11(appContext,runtime);
  initialize12(appContext,runtime);
  initialize13(appContext,runtime);
  initialize14(appContext,runtime);
  initialize15(appContext,runtime);
  initialize16(appContext,runtime);
  initialize17(appContext,runtime);
  initialize18(appContext,runtime);
  initialize19(appContext,runtime);
  initialize20(appContext,runtime);
  initialize21(appContext,runtime);
  initialize22(appContext,runtime);
  initialize23(appContext,runtime);
  initialize24(appContext,runtime);
  initialize25(appContext,runtime);
  initialize26(appContext,runtime);
  initialize27(appContext,runtime);
  initialize28(appContext,runtime);
  initialize29(appContext,runtime);
  initialize30(appContext,runtime);
  initialize31(appContext,runtime);
  initialize32(appContext,runtime);
  initialize33(appContext,runtime);
}
